*----------------------------------*
/*/{Protheus.doc} UNIA006

@project Impressão de Boletos de Cobrança

@description Tela de Cadastro de bancos Preparados para Boletos

@author Rafael Rezende
@since 15/04/2019
@version 1.0

@return

@see www.thebestconsulting.com.br/
/*/

#Include "TOTVS.ch"

*---------------------*
User Function UNIA006()
    *---------------------*

    AxCadastro( "SZ6", "Cadastro de Bancos preparados para Boletos" )

Return